#%RAML 1.0
---
title: Node Rest Backend API
baseUri: http://api.
version: v1
/users:
    get:
        description: Return all users
        responses:
            200:
                body:
                    application/json:
                    example: |
                        {
                            "data": [
                                {}
                            ]
                        }